# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: Building project
  steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false

- job: UnitTests
  displayName: Running Unit Tests 
  dependsOn: Build
  steps:
    - script: ./gradlew :app:testDebugUnitTest
